/*
# Create trading signals, calibration state, and app settings tables

## Overview

This migration creates three tables to persist the trading platform's
core data in Supabase instead of browser localStorage / in-memory state:

1. **trading_signals** — every signal generated by the decision engine
   (entry, stop, target, outcome, calibration probability, feature vector).
2. **calibration_state** — the logistic-regression model weights, bias,
   and training samples that calibrate signal probabilities over time.
3. **app_settings** — user preferences (symbol, timeframe, indicator
   config, sound settings, active patterns/indicators, chart layers).

The app has no sign-in screen, so this is a single-tenant schema: all
policies use `TO anon, authenticated` with `USING (true)` because the
data is intentionally shared/public within this single deployment.

## 1. New Tables

### trading_signals
- `id` (text, primary key) — signal UUID generated by the decision engine
- `symbol_id` (text, not null) — e.g. 'BTCUSDT', 'EURUSD'
- `timeframe` (text, not null) — '1m','5m','15m','30m','1h','4h','1d'
- `direction` (text, not null) — 'buy' or 'sell'
- `strength` (text, not null) — 'weak','moderate','strong'
- `score` (integer, not null) — raw signal score 0-100
- `calibrated_probability` (double precision, nullable) — model-calibrated probability
- `entry_price` (double precision, not null)
- `stop_loss` (double precision, not null)
- `take_profit` (double precision, not null)
- `reason` (text, not null) — human-readable signal rationale
- `pattern` (text, nullable) — detected candlestick pattern name
- `indicators` (jsonb, not null) — full IndicatorSnapshot at signal time
- `outcome` (text, not null, default 'pending') — 'pending','win','loss','timeout'
- `is_revised` (boolean, not null, default false)
- `is_pre_close` (boolean, not null, default false)
- `revision_note` (text, nullable)
- `bars_to_resolve` (integer, not null, default 5)
- `spread` (double precision, nullable)
- `spread_source` (text, nullable) — 'live' or 'estimated'
- `recommended_expiry` (integer, not null) — seconds until signal expiry
- `feature_vector` (double precision[], not null) — array of numeric features
- `signal_time` (bigint, not null) — unix timestamp (seconds) when signal was generated
- `frozen_at` (bigint, nullable) — unix timestamp when signal was frozen
- `created_at` (timestamptz, default now()) — database insert time

### calibration_state
- `id` (uuid, primary key) — single-row table, always id = '00000000-0000-0000-0000-000000000001'
- `weights` (double precision[], not null) — logistic regression weight vector
- `bias` (double precision, not null) — model bias term
- `sample_count` (integer, not null) — number of training samples consumed
- `samples` (jsonb, not null, default '[]') — array of CalibrationSample objects
- `updated_at` (timestamptz, default now()) — last modification time

### app_settings
- `id` (uuid, primary key) — single-row table, always id = '00000000-0000-0000-0000-000000000001'
- `settings` (jsonb, not null) — full settings object (symbol, timeframe, indicators, sounds, etc.)
- `updated_at` (timestamptz, default now()) — last modification time

## 2. Security

All three tables have RLS enabled with `TO anon, authenticated` policies
for full CRUD. This is a single-tenant app with no sign-in screen — the
anon-key frontend client must be able to read and write all data.

- trading_signals: 4 policies (select/insert/update/delete), all `USING (true)` / `WITH CHECK (true)`
- calibration_state: 4 policies (select/insert/update/delete), all `USING (true)` / `WITH CHECK (true)`
- app_settings: 4 policies (select/insert/update/delete), all `USING (true)` / `WITH CHECK (true)`

## 3. Indexes

- `idx_trading_signals_symbol_timeframe` — composite index on (symbol_id, timeframe) for filtering
- `idx_trading_signals_outcome` — index on outcome for win/loss queries
- `idx_trading_signals_signal_time` — index on signal_time DESC for chronological ordering

## 4. Important Notes

1. The `trading_signals.indicators` jsonb column stores the full IndicatorSnapshot
   object (RSI, EMA, MACD, ATR, Bollinger, etc.) at the moment the signal fired.
2. The `calibration_state` table is a singleton — enforced by a CHECK constraint
   that limits the table to a single row with a fixed UUID.
3. The `app_settings` table is also a singleton with the same constraint.
4. `feature_vector` is stored as a PostgreSQL array of double precision values.
5. `signal_time` and `frozen_at` are stored as bigint (unix seconds) to match
   the app's internal timestamp representation.
*/

-- ─── trading_signals ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS trading_signals (
  id text PRIMARY KEY,
  symbol_id text NOT NULL,
  timeframe text NOT NULL CHECK (timeframe IN ('1m','5m','15m','30m','1h','4h','1d')),
  direction text NOT NULL CHECK (direction IN ('buy','sell')),
  strength text NOT NULL CHECK (strength IN ('weak','moderate','strong')),
  score integer NOT NULL CHECK (score >= 0 AND score <= 100),
  calibrated_probability double precision,
  entry_price double precision NOT NULL,
  stop_loss double precision NOT NULL,
  take_profit double precision NOT NULL,
  reason text NOT NULL,
  pattern text,
  indicators jsonb NOT NULL,
  outcome text NOT NULL DEFAULT 'pending' CHECK (outcome IN ('pending','win','loss','timeout')),
  is_revised boolean NOT NULL DEFAULT false,
  is_pre_close boolean NOT NULL DEFAULT false,
  revision_note text,
  bars_to_resolve integer NOT NULL DEFAULT 5,
  spread double precision,
  spread_source text CHECK (spread_source IS NULL OR spread_source IN ('live','estimated')),
  recommended_expiry integer NOT NULL,
  feature_vector double precision[] NOT NULL,
  signal_time bigint NOT NULL,
  frozen_at bigint,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE trading_signals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_signals" ON trading_signals;
CREATE POLICY "anon_select_signals" ON trading_signals FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_signals" ON trading_signals;
CREATE POLICY "anon_insert_signals" ON trading_signals FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_signals" ON trading_signals;
CREATE POLICY "anon_update_signals" ON trading_signals FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_signals" ON trading_signals;
CREATE POLICY "anon_delete_signals" ON trading_signals FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_trading_signals_symbol_timeframe
  ON trading_signals (symbol_id, timeframe);

CREATE INDEX IF NOT EXISTS idx_trading_signals_outcome
  ON trading_signals (outcome);

CREATE INDEX IF NOT EXISTS idx_trading_signals_signal_time
  ON trading_signals (signal_time DESC);

-- ─── calibration_state (singleton) ─────────────────────────────────

CREATE TABLE IF NOT EXISTS calibration_state (
  id uuid PRIMARY KEY DEFAULT '00000000-0000-0000-0000-000000000001',
  weights double precision[] NOT NULL,
  bias double precision NOT NULL,
  sample_count integer NOT NULL DEFAULT 0,
  samples jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT singleton_check CHECK (id = '00000000-0000-0000-0000-000000000001')
);

ALTER TABLE calibration_state ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_calibration" ON calibration_state;
CREATE POLICY "anon_select_calibration" ON calibration_state FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_calibration" ON calibration_state;
CREATE POLICY "anon_insert_calibration" ON calibration_state FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_calibration" ON calibration_state;
CREATE POLICY "anon_update_calibration" ON calibration_state FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_calibration" ON calibration_state;
CREATE POLICY "anon_delete_calibration" ON calibration_state FOR DELETE
  TO anon, authenticated USING (true);

-- ─── app_settings (singleton) ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS app_settings (
  id uuid PRIMARY KEY DEFAULT '00000000-0000-0000-0000-000000000001',
  settings jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT singleton_check CHECK (id = '00000000-0000-0000-0000-000000000001')
);

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_settings" ON app_settings;
CREATE POLICY "anon_select_settings" ON app_settings FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_settings" ON app_settings;
CREATE POLICY "anon_insert_settings" ON app_settings FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_settings" ON app_settings;
CREATE POLICY "anon_update_settings" ON app_settings FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_settings" ON app_settings;
CREATE POLICY "anon_delete_settings" ON app_settings FOR DELETE
  TO anon, authenticated USING (true);
